#!/usr/bin/env bash

gen-propositional() {
    output_file=$1; shift
    python -m proof_generation.proofs.propositional "$output_file" 
}

diff-proof() {
    actual=$1; shift
    expected=$1; shift 
    diff --color -U3 --label actual <(hexdump $actual) --label expected <(hexdump $expected)
}

cargo_unit_test() {
    cargo test
}

python_unit_test() {
    make check test
}

unit_test() {
    make
}

mkdir -p .build/proofs
prop_generated=.build/proofs/propositional.ml-proof
gen-propositional "$prop_generated"
diff-proof proofs/propositional.ml-proof "$prop_generated"
cargo run --bin host proofs/propositional.ml-proof
