[package]
name = "ml_checker_cairo"
version = "0.1.0"
authors = ["Pi2 Team at RV <pi2-dev@runtimeverification.com>", "Runtime Verification"]
description = "A Matching Logic proof checker implemented in Cairo"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
