[package]
name = "guest"
version = "0.1.0"
edition = "2021"

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3
lto = true

[profile.release]
opt-level = 3
lto = true


[workspace]

[dependencies]
# If you want to try (experimental) std support, add `features = [ "std" ]` to risc0-zkvm
risc0-zkvm = { version = "0.19.1", default-features = false }

[[bin]]
name = "guest"
path = "src/main.rs"
