name: 'Update Version'
on:
  push:
    branches:
      - 'update-deps'
      - '_update-deps/runtimeverification/pyk'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  update-versions:
    name: 'Update dependency versions'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
      - name: 'Configure GitHub user'
        run: |
          git config user.name devops
          git config user.email devops@runtimeverification.com
      - name: 'Install Poetry'
        uses: Gr1N/setup-poetry@v8
      - name: 'Update pyk release tag'
        run: |
          PYK_VERSION="$(cat deps/pyk_release)"
          sed -i 's!pyk = { git = "https://github.com/runtimeverification/pyk.git", tag = "[v0-9\.]*" }!pyk = { git = "https://github.com/runtimeverification/pyk.git", tag = "'${PYK_VERSION}'" }!' generation/pyproject.toml
          poetry -C generation update
          git add --update && git commit -m "poetry: sync poetry files pyk version ${PYK_VERSION}" || true
      - name: 'Update K release file'
        run: |
          K_VERSION=$(poetry -C generation run python3 -c 'import pyk; print(pyk.K_VERSION)')
          echo ${K_VERSION} > deps/k_release
          git add deps/k_release && git commit -m "deps/k_release: sync release file version ${K_VERSION}" || true
      - name: 'Push updates'
        run: git push
